import Head from 'next/head'
import { useRouter } from 'next/router'
import CoinChartContainer from '../../components/CoinChartContainer'
import Navbar from '/components/Navbar'

export default function CoinHome() {
    const router=useRouter();
    const {slug}=router.query;
    return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    
      <main>
        <Navbar/>
        <CoinChartContainer slug={slug}/>
      </main>
    </div>
  )
}
